spring:
  application:
    name: 17-JRTP701-DataCollection-Service
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql:///jrtp701-ish-project
      username: root
      password: 123456
  jpa:
    hibernate:
        ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
---
server:
    port: 9710
---
#spring:
#  jackson:
#    date-format: MM/dd/yyyy
